# Generated by Django 3.1.5 on 2021-01-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='option1',
            new_name='option_1',
        ),
    ]
