# Generated by Django 3.1.5 on 2021-01-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210130_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='option_1',
            new_name='option1',
        ),
    ]
