# Generated by Django 3.1.5 on 2021-01-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210130_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.DateField(default=1990, verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='option1',
            field=models.CharField(max_length=100, verbose_name='Opción 1'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='option2',
            field=models.CharField(max_length=100, verbose_name='Opción 2'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='option3',
            field=models.CharField(max_length=100, verbose_name='Opción 3'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='option4',
            field=models.CharField(max_length=100, verbose_name='Opción 4'),
        ),
    ]
