# Generated by Django 3.1.5 on 2021-01-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210130_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(verbose_name='Fecha(año-mes-día)'),
        ),
    ]
