# Generated by Django 3.1.5 on 2021-01-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210130_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=100, verbose_name='Opción 1')),
                ('option2', models.CharField(max_length=100, verbose_name='Opción 2')),
                ('option3', models.CharField(max_length=100, verbose_name='Opción 3')),
                ('option4', models.CharField(max_length=100, verbose_name='Opción 4')),
            ],
        ),
        migrations.DeleteModel(
            name='carta',
        ),
    ]
