# Generated by Django 3.1.5 on 2021-01-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20210130_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.DateField(default=2008, verbose_name='Fecha(año-mes-día)'),
            preserve_default=False,
        ),
    ]
