# Generated by Django 3.1.5 on 2021-01-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
