# Generated by Django 3.1.5 on 2021-01-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20210130_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(verbose_name='Fecha(año-mes-día)'),
        ),
    ]
