# Generated by Django 3.1.5 on 2021-02-02 23:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210202_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 2, 2, 23, 40, 12, 208360, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
