# Generated by Django 3.1.5 on 2021-02-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='requested',
        ),
    ]
