# Generated by Django 3.1.5 on 2021-02-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(default='name', max_length=40),
        ),
    ]
